- name: Setup & run jenkins container
  hosts: ci-cd
  tasks:
    - name: Run jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk17
        state: started
        ports:
          - "8080:8080"
        volumes:
          - jenkins-data:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker
        networks:
          - name: ci_network
        restart_policy: "always"
