---
- name: Setup Nginx in Docker
  hosts: ci-cd
  remote_user: azureuser
  become: true

  tasks:
    - name: Copy Nginx configuration file
      copy:
        src: ./nginx/nginx.conf
        dest: /home/azureuser/nginx.conf

    - name: Copy Dockerfile
      copy:
        src: ./nginx/Dockerfile
        dest: /home/azureuser/Dockerfile

    - name: Build Nginx Docker image
      command: docker build -t my-nginx /home/azureuser

    - name: Create a volume to store SSL certificates
      community.docker.docker_volume:
        name: certs

    - name: Run Nginx container
      docker_container:
        name: nginx-proxy
        image: my-nginx
        state: started
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - certs:/etc/letsencrypt
        networks:
          - name: ci_network