- name: Create users and add SSH keys
  hosts: ci-cd
  become: yes
  vars:
    users:
      - username: mgarbowski
        full_name: Mikołaj Garbowski
      - username: mbienkowski
        full_name: Maksym Bienkowski
      - username: mluszczek
        full_name: Michał Łuszczek
      - username: jgrabski
        full_name: Jędrzej Grabski
      - username: adrwal
        full_name: Aleksander Drwal

  tasks:
    - name: Ensure group pis exists
      group:
        name: pis
        state: present

    - name: Ensure users are created and added to groups
      loop: "{{ users }}"
      user:
        name: "{{ item.username }}"
        shell: /bin/bash
        groups: docker,pis,sudo
        append: yes
        comment: "{{ item.full_name }}"

    - name: Add SSH keys for users
      loop: "{{ users }}"
      ansible.posix.authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ lookup('file', 'public_keys/' + item.username) }}"
