- name: Setup & run jenkins container
  hosts: ci-cd
  become: yes
  tasks:
    - name: Run dind for jenkins
      community.docker.docker_container:
        name: jenkins-docker
        image: docker:dind
        state: started
        restart_policy: "always"
        privileged: true
        networks:
          name: ci_network
        published_ports:
          - "2376:2376"
        env:
          DOCKER_TLS_CERTDIR: /certs
        volumes:
          - jenkins-docker-certs:/certs/client
        storage_opts:
          driver: overlay2
    - name: Run jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk17
        state: started
        ports:
          - "8080:8080"
        volumes:
          - jenkins-data:/var/jenkins_home
        networks:
          - name: ci_network
        restart_policy: "always"
